type: app
database: pg
language: slang
model: granite

# list of tasks to be run by `amber watch`
watch:
  # NOTE: names that match crystal commands are special (e.g. run, spec)
  run:
    # commands will be joined with && (join them yourself if need || or ;)
    build_commands:
      - mkdir -p bin
      - crystal build ./src/first_amber_app.cr -o bin/first_amber_app
    run_commands:
      - bin/first_amber_app
    include:
      - ./config/**/*.cr
      - ./config/environments/*.yml
      - ./src/**/*.cr
      - ./src/**/*.ecr
      - ./src/views/**/*.slang
    # exclude: # NOTE simplistic implementation: (1) enumerate all includes and excludes; (2) return (includes - excludes)
    #  - ./src/some_irrelevant_file.cr
  spec:
    run_commands:
      - crystal spec
    include:
      - ./spec/**/*.cr
  npm:
    build_commands:
      - npm install --loglevel=error
    run_commands:
      - npm run watch
